php:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: php-container
  ports:
    - "8000:80"
  volumes:
    - ./backend:/var/www/html/backend
  depends_on:
    - mysql

mysql:
  image: mysql:5.7
  container_name: mysql-container
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: scandiweb
    MYSQL_USER: user
    MYSQL_PASSWORD: user_password
  volumes:
    - mysql-data:/var/lib/mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  ports:
    - "8080:80"
  environment: 
    PMA_HOST: mysql-container
    MYSQL_ROOT_PASSWORD: root_password
  depends_on:
    - mysql

volumes:
  mysql-data:
